version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: msf_postgres
    environment:
      POSTGRES_PASSWORD: msf_password
      POSTGRES_USER: msf_user
      POSTGRES_DB: msf_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msf_user -d msf_database"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
